//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageGroupMVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public int ve_codigo { get; set; }
        public string ve_nombre { get; set; }
        public string ve_apellido { get; set; }
        public string ve_numero_identificacion { get; set; }
        public Nullable<int> ve_codigo_ciudad { get; set; }
        public string ve_estado { get; set; }
    }
}
